### ISSUE TITLE
API KEYs

### ISSUE THREAD

**Issue by Kolvir73** [mlabeeb03/trading-bots#1]
I hope that the api keys in the test bot aren't real.

**Comment by mlabeeb03** [comment]
They are expired.

**Comment by Kolvir73** [comment]
Good. I thought I had stumbled onto a file that was uploaded with current ones mistakenly. I should have know that you wouldn't make that mistake.
 I was reading about some crypto hacks the other day and it has made me  jumpy.

On Tuesday 30 May 2023 01:25:04 AM (-05:00), Muhammad Labeeb wrote:



They are expired.
